### PR TITLE
Fix enemy stuck in wall

### LINKED ISSUE #136: Enemy stuck in wall
image

### PR DESCRIPTION
**Pull request by daniellimws**
The current implementation of `TracePolygon` requires the bitmap to be padded by one unit around all four sides. Currently `RegionParseInfo` wrongly contains the padded bitmap. This causes `EnemySpawner` to spawn some enemies in the walls, as everything is off by one unit. This is fixed by only adding the padding inside `PolygonFromBitmap`.

Fix #136

### CODE REVIEW

File: Scripts/Generator/MapLoader.cs [hunk 1]
```diff
@@ -288,9 +292,10 @@ private Vector2[][] PolygonFromBitmap(bool[,] bitmap)
             for (int x = 0; x < nsize; ++x)
             {
                 if (visitedCell[x, y]) continue;
-                if (!bitmap[x, y] && bitmap[x, y + 1])
+                // want to start tracing when a cell is "off" and has an "on" cell below it
+                if (!paddedBitmap[x, y] && paddedBitmap[x, y + 1])
                 {
-                    points.Add(TracePolygon(bitmap, visitedCell, x, y));
+                    points.Add(TracePolygon(paddedBitmap, visitedCell, x, y));
```
Comment (jeffsieu) [inline Scripts/Generator/MapLoader.cs:318]: Want to change the variable name in `private Vector2[] TracePolygon(bool[,] bitmap, bool[,] visitedCell, int startX, int startY)` to `paddedBitmap` also?

**Review by jeffsieu — APPROVED** [review]

File: Scripts/Generator/Room.cs [hunk 2]
```diff
@@ -31,13 +31,13 @@ public Room(Vector2[][] polygon, Vector2[] tiles, int unitSize, Material materia
...
-            Polygon = polygon[0]
+            Polygon = regionShape.MainPolygon
         };
-        for (int i = 1; i < polygon.Length; ++i)
+        for (int i = 0; i < regionShape.HolePolygons.Length; ++i)
         {
             CSGPolygon holeMesh = new CSGPolygon
             {
-                Polygon = polygon[i],
+                Polygon = regionShape.HolePolygons[i],
```
Comment (jeffsieu) [inline Scripts/Generator/Room.cs]: Want to use
```cs
foreach (Vector2[] holePolygon in regionShape.HolePolygons)
{
    ...
    CSGPolygon holeMesh = new CSGPolygon
    {
        Polygon = holePolygon,
        ...
    }
    ...
}
```
instead?

File: Scripts/Generator/Wall.cs [hunk 3]
```diff
@@ -4,23 +4,23 @@
...
         CSGPolygon wallMesh = new CSGPolygon
         {
-            Polygon = polygon[0],
+            Polygon = regionShape.MainPolygon,
             Material = material,
             Depth = WALL_HEIGHT
         };
 
-        for (int i = 1; i < polygon.Length; ++i)
+        for (int i = 0; i < regionShape.HolePolygons.Length; ++i)
```
Comment (jeffsieu) [inline Scripts/Generator/Wall.cs]: And here also `foreach`

**Review by jeffsieu — CHANGES_REQUESTED** [review]

**Review by jeffsieu — APPROVED** [review]

**Comment by jeffsieu** [comment]
LGTM
